import { Seeder } from 'typeorm-extension';
import { DataSource } from 'typeorm';
import { Patient } from '@/modules/medical/patients/entities/patient.entity';
import { PatientStatus, RegistrationSource } from '@shared/common';

export default class PatientSeeder1 implements Seeder {
  track = false;

  public async run(dataSource: DataSource): Promise<void> {
    const patientRepository = dataSource.getRepository(Patient);
    const accidentLocationBocaUchire = 'Accidente Clarines - Boca de Uchire';
    const hospitalDomingoLuciani = 'Domingo Luciani';

    const patientsData = [
      // ===== PACIENTES DEL ACCIDENTE CLARINES - BOCA DE UCHIRE =====
      {
        dni: '31075359',
        fullName: 'María Oñales',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '22434382',
        fullName: 'Andrés Samuel',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '19933972',
        fullName: 'Alejandra Pérez',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '33303063',
        fullName: 'Nobelis Chacón',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '28386796',
        fullName: 'María Mondragón',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '32297160',
        fullName: 'Saray Paradas',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-1',
        fullName: 'Ormarlys Vargas (9 años)',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '23889912',
        fullName: 'Florisa González',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '18936530',
        fullName: 'Omar Vegas',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-2',
        fullName: 'Amelia Villalobos (9 años)',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '28820207',
        fullName: 'Vilmaris Marín',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '22034604',
        fullName: 'Darwin Parra',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '31423525',
        fullName: 'Orcarly Reina',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '29619237',
        fullName: 'Brandon Zerpa',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '26820084',
        fullName: 'Frayelis Moreno',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '19846153',
        fullName: 'María Pineda',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '28484885',
        fullName: 'Gabriela Acosta',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      // Nota: El #18 de la imagen (Andrés Samuel 22434382) es un duplicado exacto del #2. Se omite para evitar error UNIQUE.
      {
        dni: '23624685',
        fullName: 'Carmelys Rojas',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '23638704',
        fullName: 'Douglas Villalobos',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '27679002',
        fullName: 'Edward Agreda',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '28115709',
        fullName: 'José Ruiz',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-3',
        fullName: 'Yusanny Mariela',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '18836028',
        fullName: 'Yunarys Montaño',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-4',
        fullName: 'Jousbel Sousa Bracamonte (15 años)',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-5',
        fullName: 'Emilio Jiménez (Conductor)',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-6',
        fullName: 'Jose Luis Sousa (Papá)',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '34778257',
        fullName: 'Josibeth Sousa (Hermana)',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '21201094',
        fullName: 'Luiz Andres Aguilera',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-7',
        fullName: 'Nexibeth Bracamonte (Mamá)',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },

      // ===== PACIENTES DEL TERREMOTO VENEZUELA - DOMINGO LUCIANI =====
      {
        dni: '30244918',
        fullName: 'VILCHEZ VILLALOBOS BRAYAN JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32200735',
        fullName: 'RODRIGUEZ MENDEZ YOANDERLIN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '15658725',
        fullName: 'FUENTES ALBERTO JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6399935',
        fullName: 'PEREZ DE BURGOS FRANCISCA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-1',
        fullName: 'MARABITO ESPITIA JOSEANI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18134813',
        fullName: 'ABELLO WILMARI MATILDE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '8582370',
        fullName: 'RODRIGUEZ SOTO EDUARDO JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5311847',
        fullName: 'DIVITO FALLORE ROSA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31341194',
        fullName: 'GUERRERO CAMPO DEIVISON JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-2',
        fullName: 'CORDOVA GONZALEZ ARNALDO RAFAEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24998762',
        fullName: 'REY GONZALEZ JENNICEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6691779',
        fullName: 'RIVERO LOPEZ DANIEL ANΝΤΟΝΙΟ',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '12162906',
        fullName: 'RIVERO OVALLES JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '22851004',
        fullName: 'GUERRA CARLOS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34332979',
        fullName: 'DASILVA ANTHONY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30369681',
        fullName: 'DASILVA ENGELBERTH',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '21133027',
        fullName: 'RANGEL IDERLYN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '10858768',
        fullName: 'GUARDIA JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32334040',
        fullName: 'VASQUEZ ROSARIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11934645',
        fullName: 'VEGUIDA MAURO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16803900',
        fullName: 'ISCALA JENNY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13374764',
        fullName: 'DE CASTILLO LUCI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30314231',
        fullName: 'GALVIS YALESKA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27439695',
        fullName: 'GONZALEZ YAILIN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25969769',
        fullName: 'RODRIGUEZ JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9096241',
        fullName: 'CELIS TANIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '10582063',
        fullName: 'BALAS ESMERALDA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30041612',
        fullName: 'BALAS LAURA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '15488399',
        fullName: 'HENRIQUE IZQUIEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-3',
        fullName: 'GUERRERO JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27129733',
        fullName: 'ARIAS FRAN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30064183',
        fullName: 'MARIN ANTONELLA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '20558903',
        fullName: 'ECHARRY LEIDY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-10',
        fullName: 'FERNANDEZ EMILY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '1446454',
        fullName: 'DE CESPE YOLANDA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-5',
        fullName: 'SILVA JOAIBER',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '21622464',
        fullName: 'FERNANDEZ YUSQUEIDY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-6',
        fullName: 'SILVA YANDRY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '37491718',
        fullName: 'TORRES LUNA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11057636',
        fullName: 'SANDOVAL NELY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '21204553',
        fullName: 'RODRIGUEZ GERAMI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32052132',
        fullName: 'GUZMAN PAOLA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25176001',
        fullName: 'RAMIREZ NAIROBI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27678425',
        fullName: 'CARDOZA CARLA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '29815405',
        fullName: 'SALAZAR ELEN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18140377',
        fullName: 'GONZALEZ CARLOS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11636506',
        fullName: 'BOADA EVELIN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24208194',
        fullName: 'RODAS ALSEIRA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32771433',
        fullName: 'MARRERO NOHEMI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '1458202',
        fullName: 'SEPE ACHILLE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18141519',
        fullName: 'PEDRON DAVID',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27441738',
        fullName: 'ALVAREZ VALERI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13357989',
        fullName: 'RIVAS BRISET',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33285940',
        fullName: 'RIVAS SANTIAGO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-7',
        fullName: 'PEREZ ELIOMAR',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34055465',
        fullName: 'PEREZ DAENYI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18485859',
        fullName: 'BENCOMO NORKIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9995694',
        fullName: 'RENGIFO ADELSO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11639045',
        fullName: 'CASTRO ERICK',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6493087',
        fullName: 'GONCALVES LUCI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9367874',
        fullName: 'SANCHEZ CATALINA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19368106',
        fullName: 'CARRASQUEL SANTIAGO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11691451',
        fullName: 'TORTOZA JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18215359',
        fullName: 'AGUILERA YULEIMI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '2977725',
        fullName: 'FERRER BRUCE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33066249',
        fullName: 'SUAREZ JULIO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25123984',
        fullName: 'SERRANO OMAIRA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-8',
        fullName: 'GARUFF JEAN FRANCO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '20559349',
        fullName: 'MARRUFO ARIANA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33916334',
        fullName: 'FIGUERA CORDERO ADAN JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '10801488',
        fullName: 'GARRERA CASTILLO JOSE EZEQUIEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31954864',
        fullName: 'MAYORA SANJUAN JESUS DAVID',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '20007393',
        fullName: 'HUGUETO GONZALEZ KIMBERLY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19445341',
        fullName: 'RUIZ OFERMAN DENIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '22336934',
        fullName: 'MORINO GISMELI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18323401',
        fullName: 'ODUBER MANUEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '14387306',
        fullName: 'MENDOZA CARMEN',
        currentStatus: PatientStatus.DESAPARECIDO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31954864-B',
        fullName: 'MAYORCA SAN JUAN JESUS DAVID',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '26327685',
        fullName: 'CARIDA CAICEDO VICTORIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5609377',
        fullName: 'RODRIGUEZ CARRERO MARIA.',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '28304997',
        fullName: 'MARQUEZ GAURIA ANA FRANCIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18515903',
        fullName: 'ALBARACIL DANIELA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32141445',
        fullName: 'BORGES HERRERA LILIANY N',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27190139',
        fullName: 'ALAYON DIAZ SUYIN SINAΙ',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11314662',
        fullName: 'ROJAS REYES RAFAEL ERNESTO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30464608',
        fullName: 'GONZALEZ NAVARRO STEFHANY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17709451',
        fullName: 'GONZALEZ RANGEL RAFAEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-9',
        fullName: 'CASTRO JUAN ERNESTO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6693609',
        fullName: 'ESCALONA ARVELO IVIS MILEIDY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '7997334',
        fullName: 'SERRANO NANCY DEL VALLE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6894583',
        fullName: 'ROMERO LISCANO JOSE LUIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24336559',
        fullName: 'GUAIRINI PADRON EFREN DE JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9666949',
        fullName: 'CISNERO ROSA ELENA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5982195',
        fullName: 'MUÑOZ JURENCIA JOSEFINA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9947561',
        fullName: 'ORDAZ CARRION LUISANA RAMONA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '37772606',
        fullName: 'MACHADO ANARELLA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '10582260',
        fullName: 'FRONTADO MIEL REINA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '22764817',
        fullName: 'JIMENEZ LOPEZ AXIEL DAVIANGEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6479370',
        fullName: 'PEDRON JESUS CIRILIO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24801393',
        fullName: 'GOYO ORDAZ RAFAEL ALEJANDRO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33101293',
        fullName: 'DONACIENTO MARTINEZ SEBASTIAN',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6331767',
        fullName: 'BLANCO CARMEN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25862641',
        fullName: 'CABRERA YENDERLIN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34064137',
        fullName: 'SEQUERA SOFIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34056071',
        fullName: 'SALAZAR ARTURO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '12138770',
        fullName: 'RIVAS FRANKLIN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17710539',
        fullName: 'PORTILLO OMAR JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6484464',
        fullName: 'SUAREZ RENE JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '14805380',
        fullName: 'LEWIS CALDERA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16106589',
        fullName: 'PADILLA RODOSKI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24942164',
        fullName: 'RAMIREZ MARIANGEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24896082',
        fullName: 'BOMPART ROTNY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '29815388',
        fullName: 'RIVAS RIVAS FABIANA PAOLA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31745693',
        fullName: 'MILANO HERRERA GLADIUSKA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6311703',
        fullName: 'MUÑOZ BELLORIN MARIANGEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16106589-B',
        fullName: 'VASRONCILOS GARCES ANDREINA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '12162787',
        fullName: 'PADILLA RODOSKI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33101293-B',
        fullName: 'PRIETO MARTINEZ SEBASTIAN D',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11635019',
        fullName: 'BLANCO YESSTY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16309658',
        fullName: 'BARRETO FERNANDEZ RICARDO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34004259',
        fullName: 'OBREGON ROJAS DIEGO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25683044',
        fullName: 'RODRIGUEZ CABRERA KARINA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16234835',
        fullName: 'GONZALEZ ALEXANDER',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34005746',
        fullName: 'CHACON G CARLOS ALEXANDER',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-10',
        fullName: 'LOPEZ HADDY',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-11',
        fullName: 'CASTILLO VICTORIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '36111155',
        fullName: 'CASTAÑO PALACIOS DANNA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17154439',
        fullName: 'TORRES MILAGROS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34037224',
        fullName: 'PARRA GABRIELA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '36144414',
        fullName: 'ARTEAGA HALLY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27678425-B',
        fullName: 'CARDOZO CARLOS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-12',
        fullName: 'MARTINEZ JHOAN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-13',
        fullName: 'MARTINEZ JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13571612',
        fullName: 'CASTAÑO CARLOS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5894212',
        fullName: 'CASTAÑEDA MARIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '23613612',
        fullName: 'RAMIREZ JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '8376384',
        fullName: 'PALMA JULIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25464507',
        fullName: 'GONZALEZ TOVAR VALERI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19275667',
        fullName: 'MARTINEZ RIOS SANTIAGO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '26327913',
        fullName: 'CASTILLO VALERIO IASKARA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13374764-B',
        fullName: 'DE CASTILLO LUCY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-14',
        fullName: 'HUGA ANDERSON',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32869625',
        fullName: 'TRUJILLO HERIAM',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-15',
        fullName: 'ASCANIO LUIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '21192584',
        fullName: 'DUGARTE LOPEZ IREALY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '15810755',
        fullName: 'ROSA MORE JOSE ANGEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5979453',
        fullName: 'MARTINEZ ROJAS MARCELA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '15831697',
        fullName: 'YACIZ YELITZA ODALI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11058065',
        fullName: 'FARIÑEZ BELIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31291495',
        fullName: 'REBOLLEDO GUARDIA LUIS MARIANO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11058565',
        fullName: 'SANCHEZ FARIÑA ARELIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16116675',
        fullName: 'VEGA ROMERO ISABEL VEGA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18753433',
        fullName: 'ACEVEDO NAYIBETH',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34034386',
        fullName: 'RODRIGUEZ ACEVEDO CAMILA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '3783260',
        fullName: 'BETANCOURT MARIA',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-16',
        fullName: 'IZQUIERDO JEAN',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-17',
        fullName: 'VASQUEZ LUIS',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '22782771',
        fullName: 'FERNANDEZ EFRAIN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9855602',
        fullName: 'MARCANO KATISUSKA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6511409',
        fullName: 'ALVES MANUEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6270109',
        fullName: 'GONZALEZ ALBYMAR',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24318471',
        fullName: 'WINCHESTER KELLYS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '14274838',
        fullName: 'MIJARES ISOLIBETH',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6370687',
        fullName: 'BORGES BECERRA CARMEN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30654788',
        fullName: 'MENDEZ YESIRET',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '2156070',
        fullName: 'URBINA SILIBERTO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6693479',
        fullName: 'GUEVARA YOSELY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13557842',
        fullName: 'ACOSTA ALI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9953482',
        fullName: 'YANEZ YELITZA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '22061324',
        fullName: 'PEREZ ANGIE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11966827',
        fullName: 'VEGAS MARIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33420425',
        fullName: 'ARELLANO CAMILA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-18',
        fullName: 'TORRES LUIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '28037310',
        fullName: 'SANCHEZ STEVEN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27858660',
        fullName: 'BOLIVAR DIOSCARLY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9367804',
        fullName: 'SANCHEZ CATALINA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6396589',
        fullName: 'VIERRA RAMIREZ MARIA CARIDAD',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '4851620',
        fullName: 'OVIEDO NOGUERA JORGUE LUIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '4542986',
        fullName: 'BAEZ DE SALAS GLORIA YAJAIRA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17386172',
        fullName: 'HERNANDEZ QUERALES DEILY JAVIER',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '12669657',
        fullName: 'ORIHUELA FRANCO LILIANA COROMOTO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19122776',
        fullName: 'VERA DELGADO JOSE LUIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9914674',
        fullName: 'REQUENA DILIA RAMONA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19627944',
        fullName: 'GUERRA PINO ROSA MARIBEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '3802781',
        fullName: 'ARREAZA ARREAZA MAURICIO DE JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '2155100',
        fullName: 'DIAZ PUNCELES ESCARLET TERESA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6273270',
        fullName: 'QUINTERO DAVILA PEDRO MIGUEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30887105',
        fullName: 'ERAZO RANGEL HARRY VLADIMIR',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '26327348',
        fullName: 'JERRY ESCOBAR MAR',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '21478247',
        fullName: 'RODRIGUEZ NOGUERA NAIFER',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9998618',
        fullName: 'GIL MACHIL MAIRA MARIBE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '7266866',
        fullName: 'FEBLES CLAUDIO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '26368632',
        fullName: 'PUELLO BLANCO YULEIDY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30909930',
        fullName: 'DIAZ ABREU ANYELI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31308884',
        fullName: 'BLANCO DIAS SAMUEL A.',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17769820',
        fullName: 'QUESADA ZAMARRA WILFRED',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11640417',
        fullName: 'APONTE LIENDO ERNESTO JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '14313018',
        fullName: 'BARROETA IZAGUIRRE YOLANDA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6483724',
        fullName: 'BAUTE MINELY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '36905651',
        fullName: 'LOPEZ MORA VALERI ALEXANDRA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
    ];

    // Utilizamos upsert por 'dni' para evitar errores de duplicidad si corres el seeder varias veces
    for (const patient of patientsData) {
      await patientRepository.upsert(patient, ['dni']);
    }

    console.log('Seeder de pacientes ejecutado con éxito.');
  }
}
