import { Seeder } from 'typeorm-extension';
import { DataSource } from 'typeorm';
import { Patient } from '@/modules/medical/patients/entities/patient.entity';
import { PatientStatus, RegistrationSource } from '@shared/common';

export default class PatientSeeder1 implements Seeder {
  track = false;

  public async run(dataSource: DataSource): Promise<void> {
    const patientRepository = dataSource.getRepository(Patient);
    const accidentLocationBocaUchire = 'Accidente Clarines - Boca de Uchire';
    const hospitalDomingoLuciani = 'Domingo Luciani';

    const patientsData = [
      // ===== PACIENTES DEL ACCIDENTE CLARINES - BOCA DE UCHIRE =====
      {
        dni: '31075359',
        fullName: 'María Oñales',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '22434382',
        fullName: 'Andrés Samuel',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '19933972',
        fullName: 'Alejandra Pérez',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '33303063',
        fullName: 'Nobelis Chacón',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '28386796',
        fullName: 'María Mondragón',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '32297160',
        fullName: 'Saray Paradas',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-1',
        fullName: 'Ormarlys Vargas (9 años)',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '23889912',
        fullName: 'Florisa González',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '18936530',
        fullName: 'Omar Vegas',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-2',
        fullName: 'Amelia Villalobos (9 años)',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '28820207',
        fullName: 'Vilmaris Marín',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '22034604',
        fullName: 'Darwin Parra',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '31423525',
        fullName: 'Orcarly Reina',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '29619237',
        fullName: 'Brandon Zerpa',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '26820084',
        fullName: 'Frayelis Moreno',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '19846153',
        fullName: 'María Pineda',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '28484885',
        fullName: 'Gabriela Acosta',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      // Nota: El #18 de la imagen (Andrés Samuel 22434382) es un duplicado exacto del #2. Se omite para evitar error UNIQUE.
      {
        dni: '23624685',
        fullName: 'Carmelys Rojas',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '23638704',
        fullName: 'Douglas Villalobos',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '27679002',
        fullName: 'Edward Agreda',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '28115709',
        fullName: 'José Ruiz',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-3',
        fullName: 'Yusanny Mariela',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '18836028',
        fullName: 'Yunarys Montaño',
        currentStatus: PatientStatus.ESTABLE,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-4',
        fullName: 'Jousbel Sousa Bracamonte (15 años)',
        currentStatus: PatientStatus.CRITICO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-5',
        fullName: 'Emilio Jiménez (Conductor)',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-6',
        fullName: 'Jose Luis Sousa (Papá)',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '34778257',
        fullName: 'Josibeth Sousa (Hermana)',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: '21201094',
        fullName: 'Luiz Andres Aguilera',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },
      {
        dni: 'S/N-7',
        fullName: 'Nexibeth Bracamonte (Mamá)',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: accidentLocationBocaUchire,
        registrationSource: RegistrationSource.MEDICAL_STAFF,
      },

      // ===== PACIENTES DEL TERREMOTO VENEZUELA - DOMINGO LUCIANI =====
      {
        dni: '30244918',
        fullName: 'VILCHEZ VILLALOBOS BRAYAN JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32200735',
        fullName: 'RODRIGUEZ MENDEZ YOANDERLIN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '15658725',
        fullName: 'FUENTES ALBERTO JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6399935',
        fullName: 'PEREZ DE BURGOS FRANCISCA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-1',
        fullName: 'MARABITO ESPITIA JOSEANI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18134813',
        fullName: 'ABELLO WILMARI MATILDE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '8582370',
        fullName: 'RODRIGUEZ SOTO EDUARDO JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5311847',
        fullName: 'DIVITO FALLORE ROSA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31341194',
        fullName: 'GUERRERO CAMPO DEIVISON JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-2',
        fullName: 'CORDOVA GONZALEZ ARNALDO RAFAEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24998762',
        fullName: 'REY GONZALEZ JENNICEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6691779',
        fullName: 'RIVERO LOPEZ DANIEL ANΝΤΟΝΙΟ',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '12162906',
        fullName: 'RIVERO OVALLES JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '22851004',
        fullName: 'GUERRA CARLOS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34332979',
        fullName: 'DASILVA ANTHONY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30369681',
        fullName: 'DASILVA ENGELBERTH',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '21133027',
        fullName: 'RANGEL IDERLYN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '10858768',
        fullName: 'GUARDIA JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32334040',
        fullName: 'VASQUEZ ROSARIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11934645',
        fullName: 'VEGUIDA MAURO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16803900',
        fullName: 'ISCALA JENNY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13374764',
        fullName: 'DE CASTILLO LUCI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30314231',
        fullName: 'GALVIS YALESKA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27439695',
        fullName: 'GONZALEZ YAILIN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25969769',
        fullName: 'RODRIGUEZ JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9096241',
        fullName: 'CELIS TANIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '10582063',
        fullName: 'BALAS ESMERALDA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30041612',
        fullName: 'BALAS LAURA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '15488399',
        fullName: 'HENRIQUE IZQUIEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-3',
        fullName: 'GUERRERO JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27129733',
        fullName: 'ARIAS FRAN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30064183',
        fullName: 'MARIN ANTONELLA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '20558903',
        fullName: 'ECHARRY LEIDY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-10',
        fullName: 'FERNANDEZ EMILY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '1446454',
        fullName: 'DE CESPE YOLANDA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-5',
        fullName: 'SILVA JOAIBER',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '21622464',
        fullName: 'FERNANDEZ YUSQUEIDY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-6',
        fullName: 'SILVA YANDRY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '37491718',
        fullName: 'TORRES LUNA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11057636',
        fullName: 'SANDOVAL NELY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '21204553',
        fullName: 'RODRIGUEZ GERAMI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32052132',
        fullName: 'GUZMAN PAOLA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25176001',
        fullName: 'RAMIREZ NAIROBI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27678425',
        fullName: 'CARDOZA CARLA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '29815405',
        fullName: 'SALAZAR ELEN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18140377',
        fullName: 'GONZALEZ CARLOS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11636506',
        fullName: 'BOADA EVELIN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24208194',
        fullName: 'RODAS ALSEIRA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32771433',
        fullName: 'MARRERO NOHEMI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '1458202',
        fullName: 'SEPE ACHILLE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18141519',
        fullName: 'PEDRON DAVID',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27441738',
        fullName: 'ALVAREZ VALERI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13357989',
        fullName: 'RIVAS BRISET',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33285940',
        fullName: 'RIVAS SANTIAGO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-7',
        fullName: 'PEREZ ELIOMAR',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34055465',
        fullName: 'PEREZ DAENYI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18485859',
        fullName: 'BENCOMO NORKIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9995694',
        fullName: 'RENGIFO ADELSO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11639045',
        fullName: 'CASTRO ERICK',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6493087',
        fullName: 'GONCALVES LUCI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9367874',
        fullName: 'SANCHEZ CATALINA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19368106',
        fullName: 'CARRASQUEL SANTIAGO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11691451',
        fullName: 'TORTOZA JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18215359',
        fullName: 'AGUILERA YULEIMI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '2977725',
        fullName: 'FERRER BRUCE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33066249',
        fullName: 'SUAREZ JULIO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25123984',
        fullName: 'SERRANO OMAIRA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-8',
        fullName: 'GARUFF JEAN FRANCO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '20559349',
        fullName: 'MARRUFO ARIANA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33916334',
        fullName: 'FIGUERA CORDERO ADAN JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '10801488',
        fullName: 'GARRERA CASTILLO JOSE EZEQUIEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31954864',
        fullName: 'MAYORA SANJUAN JESUS DAVID',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '20007393',
        fullName: 'HUGUETO GONZALEZ KIMBERLY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19445341',
        fullName: 'RUIZ OFERMAN DENIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '22336934',
        fullName: 'MORINO GISMELI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18323401',
        fullName: 'ODUBER MANUEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '14387306',
        fullName: 'MENDOZA CARMEN',
        currentStatus: PatientStatus.DESAPARECIDO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31954864-B',
        fullName: 'MAYORCA SAN JUAN JESUS DAVID',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '26327685',
        fullName: 'CARIDA CAICEDO VICTORIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5609377',
        fullName: 'RODRIGUEZ CARRERO MARIA.',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '28304997',
        fullName: 'MARQUEZ GAURIA ANA FRANCIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18515903',
        fullName: 'ALBARACIL DANIELA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32141445',
        fullName: 'BORGES HERRERA LILIANY N',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27190139',
        fullName: 'ALAYON DIAZ SUYIN SINAΙ',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11314662',
        fullName: 'ROJAS REYES RAFAEL ERNESTO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30464608',
        fullName: 'GONZALEZ NAVARRO STEFHANY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17709451',
        fullName: 'GONZALEZ RANGEL RAFAEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-9',
        fullName: 'CASTRO JUAN ERNESTO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6693609',
        fullName: 'ESCALONA ARVELO IVIS MILEIDY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '7997334',
        fullName: 'SERRANO NANCY DEL VALLE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6894583',
        fullName: 'ROMERO LISCANO JOSE LUIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24336559',
        fullName: 'GUAIRINI PADRON EFREN DE JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9666949',
        fullName: 'CISNERO ROSA ELENA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5982195',
        fullName: 'MUÑOZ JURENCIA JOSEFINA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9947561',
        fullName: 'ORDAZ CARRION LUISANA RAMONA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '37772606',
        fullName: 'MACHADO ANARELLA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '10582260',
        fullName: 'FRONTADO MIEL REINA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '22764817',
        fullName: 'JIMENEZ LOPEZ AXIEL DAVIANGEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6479370',
        fullName: 'PEDRON JESUS CIRILIO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24801393',
        fullName: 'GOYO ORDAZ RAFAEL ALEJANDRO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33101293',
        fullName: 'DONACIENTO MARTINEZ SEBASTIAN',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6331767',
        fullName: 'BLANCO CARMEN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25862641',
        fullName: 'CABRERA YENDERLIN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34064137',
        fullName: 'SEQUERA SOFIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34056071',
        fullName: 'SALAZAR ARTURO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '12138770',
        fullName: 'RIVAS FRANKLIN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17710539',
        fullName: 'PORTILLO OMAR JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6484464',
        fullName: 'SUAREZ RENE JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '14805380',
        fullName: 'LEWIS CALDERA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16106589',
        fullName: 'PADILLA RODOSKI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24942164',
        fullName: 'RAMIREZ MARIANGEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24896082',
        fullName: 'BOMPART ROTNY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '29815388',
        fullName: 'RIVAS RIVAS FABIANA PAOLA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31745693',
        fullName: 'MILANO HERRERA GLADIUSKA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6311703',
        fullName: 'MUÑOZ BELLORIN MARIANGEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16106589-B',
        fullName: 'VASRONCILOS GARCES ANDREINA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '12162787',
        fullName: 'PADILLA RODOSKI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33101293-B',
        fullName: 'PRIETO MARTINEZ SEBASTIAN D',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11635019',
        fullName: 'BLANCO YESSTY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16309658',
        fullName: 'BARRETO FERNANDEZ RICARDO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34004259',
        fullName: 'OBREGON ROJAS DIEGO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25683044',
        fullName: 'RODRIGUEZ CABRERA KARINA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16234835',
        fullName: 'GONZALEZ ALEXANDER',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34005746',
        fullName: 'CHACON G CARLOS ALEXANDER',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-10',
        fullName: 'LOPEZ HADDY',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-11',
        fullName: 'CASTILLO VICTORIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '36111155',
        fullName: 'CASTAÑO PALACIOS DANNA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17154439',
        fullName: 'TORRES MILAGROS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34037224',
        fullName: 'PARRA GABRIELA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '36144414',
        fullName: 'ARTEAGA HALLY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27678425-B',
        fullName: 'CARDOZO CARLOS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-12',
        fullName: 'MARTINEZ JHOAN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-13',
        fullName: 'MARTINEZ JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13571612',
        fullName: 'CASTAÑO CARLOS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5894212',
        fullName: 'CASTAÑEDA MARIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '23613612',
        fullName: 'RAMIREZ JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '8376384',
        fullName: 'PALMA JULIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25464507',
        fullName: 'GONZALEZ TOVAR VALERI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19275667',
        fullName: 'MARTINEZ RIOS SANTIAGO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '26327913',
        fullName: 'CASTILLO VALERIO IASKARA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13374764-B',
        fullName: 'DE CASTILLO LUCY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-14',
        fullName: 'HUGA ANDERSON',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32869625',
        fullName: 'TRUJILLO HERIAM',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-15',
        fullName: 'ASCANIO LUIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '21192584',
        fullName: 'DUGARTE LOPEZ IREALY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '15810755',
        fullName: 'ROSA MORE JOSE ANGEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5979453',
        fullName: 'MARTINEZ ROJAS MARCELA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '15831697',
        fullName: 'YACIZ YELITZA ODALI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11058065',
        fullName: 'FARIÑEZ BELIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31291495',
        fullName: 'REBOLLEDO GUARDIA LUIS MARIANO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11058565',
        fullName: 'SANCHEZ FARIÑA ARELIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16116675',
        fullName: 'VEGA ROMERO ISABEL VEGA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18753433',
        fullName: 'ACEVEDO NAYIBETH',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34034386',
        fullName: 'RODRIGUEZ ACEVEDO CAMILA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '3783260',
        fullName: 'BETANCOURT MARIA',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-16',
        fullName: 'IZQUIERDO JEAN',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-17',
        fullName: 'VASQUEZ LUIS',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '22782771',
        fullName: 'FERNANDEZ EFRAIN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9855602',
        fullName: 'MARCANO KATISUSKA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6511409',
        fullName: 'ALVES MANUEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6270109',
        fullName: 'GONZALEZ ALBYMAR',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24318471',
        fullName: 'WINCHESTER KELLYS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '14274838',
        fullName: 'MIJARES ISOLIBETH',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6370687',
        fullName: 'BORGES BECERRA CARMEN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30654788',
        fullName: 'MENDEZ YESIRET',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '2156070',
        fullName: 'URBINA SILIBERTO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6693479',
        fullName: 'GUEVARA YOSELY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13557842',
        fullName: 'ACOSTA ALI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9953482',
        fullName: 'YANEZ YELITZA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '22061324',
        fullName: 'PEREZ ANGIE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11966827',
        fullName: 'VEGAS MARIA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33420425',
        fullName: 'ARELLANO CAMILA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-18',
        fullName: 'TORRES LUIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '28037310',
        fullName: 'SANCHEZ STEVEN',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27858660',
        fullName: 'BOLIVAR DIOSCARLY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9367804',
        fullName: 'SANCHEZ CATALINA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6396589',
        fullName: 'VIERRA RAMIREZ MARIA CARIDAD',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '4851620',
        fullName: 'OVIEDO NOGUERA JORGUE LUIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '4542986',
        fullName: 'BAEZ DE SALAS GLORIA YAJAIRA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17386172',
        fullName: 'HERNANDEZ QUERALES DEILY JAVIER',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '12669657',
        fullName: 'ORIHUELA FRANCO LILIANA COROMOTO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19122776',
        fullName: 'VERA DELGADO JOSE LUIS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9914674',
        fullName: 'REQUENA DILIA RAMONA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19627944',
        fullName: 'GUERRA PINO ROSA MARIBEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '3802781',
        fullName: 'ARREAZA ARREAZA MAURICIO DE JESUS',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '2155100',
        fullName: 'DIAZ PUNCELES ESCARLET TERESA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6273270',
        fullName: 'QUINTERO DAVILA PEDRO MIGUEL',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30887105',
        fullName: 'ERAZO RANGEL HARRY VLADIMIR',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '26327348',
        fullName: 'JERRY ESCOBAR MAR',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '21478247',
        fullName: 'RODRIGUEZ NOGUERA NAIFER',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9998618',
        fullName: 'GIL MACHIL MAIRA MARIBE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '7266866',
        fullName: 'FEBLES CLAUDIO',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '26368632',
        fullName: 'PUELLO BLANCO YULEIDY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30909930',
        fullName: 'DIAZ ABREU ANYELI',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31308884',
        fullName: 'BLANCO DIAS SAMUEL A.',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17769820',
        fullName: 'QUESADA ZAMARRA WILFRED',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11640417',
        fullName: 'APONTE LIENDO ERNESTO JOSE',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '14313018',
        fullName: 'BARROETA IZAGUIRRE YOLANDA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6483724',
        fullName: 'BAUTE MINELY',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '36905651',
        fullName: 'LOPEZ MORA VALERI ALEXANDRA',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        manualLocation: hospitalDomingoLuciani,
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },

      // ===== PACIENTES DEL TERREMOTO VENEZUELA - HOSPITAL PÉREZ CARREÑO =====
      {
        dni: '30072743',
        fullName: 'Yodalis Navas',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '82230906',
        fullName: 'Gabriel Joncalvez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6092167',
        fullName: 'Zoraida de Martinez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17709218',
        fullName: 'Elizabedh Gonzalez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '2945823',
        fullName: 'Petra Sotre',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16125101',
        fullName: 'Wilian Alvarez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '28143770',
        fullName: 'Alexandra Cardenas',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '285659',
        fullName: 'Francis Medina',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '4636722',
        fullName: 'Cruz Hernandez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19659867',
        fullName: 'Fran Rondon',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34800366',
        fullName: 'Leonardo Becerra',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6405488',
        fullName: 'Cenaida Paredez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27006264',
        fullName: 'Oriana Ramirez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '3883421',
        fullName: 'Yudi Paredes',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17856045',
        fullName: 'Adriano Bastido',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '20003134',
        fullName: 'Ana Aguilera',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27044236',
        fullName: 'Juan Zalazar',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30170626',
        fullName: 'Beronica Bastardo',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '29701695',
        fullName: 'Isabel Gonzales',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32976229',
        fullName: 'Elianni Idalgo',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-1',
        fullName: 'Franleydi Lopez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '29565365',
        fullName: 'Nathadia Medina',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32357883',
        fullName: 'Ibsen Iglesias',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13574764',
        fullName: 'Fleici Valero',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6059288',
        fullName: 'Maria Quillen',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27377514',
        fullName: 'Juver Garcia',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '23926261',
        fullName: 'Crisbel Granado',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19367804',
        fullName: 'Wuilliams Martinez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '15541666',
        fullName: 'Mailin Lopez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13641870',
        fullName: 'Thais Lopez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '16310014',
        fullName: 'Angel Fernandez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31428533',
        fullName: 'Genesis Bracamonte',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33020891',
        fullName: 'Samuel Peroza',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13717087',
        fullName: 'Rosalinda Viera',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '9416493',
        fullName: 'Candelario Vovis',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '14312752',
        fullName: 'Lourdes Dropeza',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-2',
        fullName: 'Milagro Palma',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-3',
        fullName: 'Rodrigo Fernandez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '4163469',
        fullName: 'Alvaro Ortiz',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '13422890',
        fullName: 'Barbara Quintero',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '26327366',
        fullName: 'Cesar Pacheco',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '10576803',
        fullName: 'Ana Dias',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17856045',
        fullName: 'Adriana Vastidas',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '2945823',
        fullName: 'Petra Sucre',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18384289',
        fullName: 'Yenni Marcano',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '296723',
        fullName: 'Manuela De Anzola',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '22916224',
        fullName: 'Gonzalo Leon',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19734177',
        fullName: 'Celiana Mijares',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5199652',
        fullName: 'Yonny Ortuño',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25699054',
        fullName: 'Ana Fernandez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6904629',
        fullName: 'Alyandra Soja',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '24038780',
        fullName: 'Eiban Yegue',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6049995',
        fullName: 'Marcela Bernal',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '28544619',
        fullName: 'Valeria Azocar',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34588981',
        fullName: 'Anabela Morillo',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5965096',
        fullName: 'Lesvia Morales',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17158021',
        fullName: 'Merido Bueno',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25025734',
        fullName: 'Maria Montolla',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '36091784',
        fullName: 'Karleidi Rivero',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '4718019',
        fullName: 'Isabel Torres',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '12115323',
        fullName: 'Dufiar Lopez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31760907',
        fullName: 'Yaneli Acosta',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '81462470',
        fullName: 'Meri Chavez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27374286',
        fullName: 'Elisabeth Chacon',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '17755829',
        fullName: 'Juan Garcia',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-4',
        fullName: 'Medina Parra Fernando Jose',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-5',
        fullName: 'Polanco Yaupoma Leon Santiago',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-6',
        fullName: 'Parica Parica Laiyum Yuque',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-7',
        fullName: 'Mia Acevedo',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-8',
        fullName: 'Brito Antonella',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-9',
        fullName: 'Gonzalez Velasquez Fabian Mauricio',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-10',
        fullName: 'Orozco Pelaez Diego',
        currentStatus: PatientStatus.CONTACTAR_INMEDIATO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-11',
        fullName: 'Vergara Blanco Aranza Seungmi',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-12',
        fullName: 'Rodriguez Oliva Joelvinger Jesus',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-13',
        fullName: 'Zuvanyeli Valentina Perez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-14',
        fullName: 'Emili Ramos',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-15',
        fullName: 'Zamora Valentina del Monte',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-16',
        fullName: 'Yordana Flores',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-17',
        fullName: 'Aron Isaac Villalobos',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32781459',
        fullName: 'Gabriel Brizuela',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33232603',
        fullName: 'Viviana Carrizo',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '33423811',
        fullName: 'Diego Garcia',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '10384289',
        fullName: 'Yenni Marcano',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '26372024',
        fullName: 'Yunior Tirado',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '28285779',
        fullName: 'Emili Mosquera',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11517536',
        fullName: 'Victor Dias',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '28100561',
        fullName: 'Maria Araque',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '14194021',
        fullName: 'Maryuri Sedeño',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18461886',
        fullName: 'Barbara Ramirez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '30678485',
        fullName: 'David Brito',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '19102824',
        fullName: 'Marlene Davila',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5613119',
        fullName: 'Maria Moreno',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '14424783',
        fullName: 'Fredy Rodriguez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '81659048',
        fullName: 'Fernanda Figuera',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '6448839',
        fullName: 'Yose Palma',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '12060080',
        fullName: 'Carmen Angarita',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '25872328',
        fullName: 'Yoandri Colina',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '31948173',
        fullName: 'Yermin Baptista',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11638321',
        fullName: 'Sandra Dias',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '11688834',
        fullName: 'Juana de Santiago',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '5199693',
        fullName: 'Yoni Ortuño',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '4281217',
        fullName: 'Ana Olivero',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '12763837',
        fullName: 'Yadira Cordero',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-18',
        fullName: 'Dayana Rondon',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32865296',
        fullName: 'Crisdeilis Quintero',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '18749225',
        fullName: 'Eric Godoy',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '29768360',
        fullName: 'Nayibi Molina',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '27044236',
        fullName: 'Maria Zamora',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '4493435',
        fullName: 'Rosa Marcano',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34518879',
        fullName: 'Adriana Sandoval',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '34054588',
        fullName: 'Victoria Miranda',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '28747519',
        fullName: 'Jose Gutierrez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: 'S/N-PC-19',
        fullName: 'Eduar Orana',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '26468240',
        fullName: 'Mileibis Gonzalez',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '26019884',
        fullName: 'Emira Guerra',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
      {
        dni: '32543420',
        fullName: 'Keilimar Garcia',
        currentStatus: PatientStatus.NO_ESPECIFICADO,
        currentMedicalCenterId: 56,
        manualLocation: 'Hospital Pérez Carreño',
        registrationSource: RegistrationSource.PUBLIC_LIST,
      },
    ];

    // ===== VALIDACIÓN DE DUPLICADOS =====
    // 1. Obtener DNIs existentes en BD
    const existingPatients = await patientRepository.find({ select: ['dni'] });
    const existingDnis = new Set(existingPatients.map((p) => p.dni));

    // 2. Registrar DNIs procesados en este mismo batch
    const processedDnis = new Set<string>();
    const skipped: { dni: string; fullName: string; reason: string }[] = [];
    let insertedCount = 0;

    console.log(`\n🔍 Verificando duplicados entre ${patientsData.length} registros...`);

    for (const patient of patientsData) {
      if (existingDnis.has(patient.dni)) {
        skipped.push({
          dni: patient.dni,
          fullName: patient.fullName,
          reason: 'Ya existe en base de datos',
        });
        continue;
      }

      if (processedDnis.has(patient.dni)) {
        skipped.push({
          dni: patient.dni,
          fullName: patient.fullName,
          reason: 'Duplicado interno en este mismo batch',
        });
        continue;
      }

      // Insertar el paciente
      await patientRepository.insert(patient);
      processedDnis.add(patient.dni);
      existingDnis.add(patient.dni); // Para evitar que otro duplicado del mismo DNI pase
      insertedCount++;
    }

    // 3. Mostrar resumen
    console.log(`\n✅ ${insertedCount} pacientes insertados correctamente.`);
    if (skipped.length > 0) {
      console.log(`\n⚠️  Se omitieron ${skipped.length} paciente(s) duplicado(s):`);
      for (const s of skipped) {
        console.log(`   - DNI: ${s.dni.padEnd(20)} | ${s.fullName.padEnd(40)} | ${s.reason}`);
      }
    }

    console.log('Seeder de pacientes ejecutado con éxito.');
  }
}
